# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azhubreader < Formula
  desc "Extract Azure Event Hub messages into JSON files"
  homepage "https://github.com/obay/azhubreader"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.2/azhubreader_Darwin_x86_64.tar.gz"
      sha256 "0c117b2963b51b32c2d3a1771133aa84b5baf9938e700b5ad6de3decd453e115"

      def install
        bin.install "azhubreader"
      end
    end
    on_arm do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.2/azhubreader_Darwin_arm64.tar.gz"
      sha256 "405f81de25a8db41da32c7ab715220415402e1980796d8a68bd85b4a45a2a0b6"

      def install
        bin.install "azhubreader"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.2/azhubreader_Linux_x86_64.tar.gz"
        sha256 "a23cc1b5017a10df27d00755963c7e6f43dca1a1fac5bb308b790714b7236230"

        def install
          bin.install "azhubreader"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.2/azhubreader_Linux_arm64.tar.gz"
        sha256 "a9bd2f2a7e8f0dcf6bd225741a667972ba7b75ee621ec68f70eed0922990a8a5"

        def install
          bin.install "azhubreader"
        end
      end
    end
  end
end
